pipeline {
    agent {
        docker {
            image 'maven:3.9.16-sapmachine-21'
            args '-v $HOME/.m2:/root/.m2'
          }
      } 

    stages {
        stage("build") {
            when {
                changeset "**/worker/**"
              }
            steps{
              echo 'building worker app'
              dir('worker') {
                  sh 'mvn compile'
                }
              }
          }
        stage("test"){
            when{
                changeset "**/worker/**"
              }
            steps{
                echo 'Running Unit Tests on worker app'
                dir('worker') {
                  sh 'mvn clean test'
                  }
              }
          }
        
        stage("package"){
            when{
                changeset "**/worker/**"
              }
            steps{
                echo 'Packaging worker app into a jarfile'
                dir('worker'){
                  sh 'mvn package -DskipTests'
                  archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
              }
          }
      }

      post{
          always{
              echo 'the job is completed.'
            }
        }
  }
